### PR TITLE
Fix: ensuring room DB instance is created only once by double-checked locking

### LINKED ISSUE #130: [Bug] Race conditions in singleton pattern of AppDatabase
### Description

Singleton pattern is poorly implemented in `AppDatabase.kt` file in `getDatabase()` method. It's expected to be double-checked singleton but it's not checking twice.

### Technical detail:  

**If two thread access `getDatabase()`:** 

1. Thread1 and Thread2 call `getDatabase()` 
2. Thread1 checks instance is null and goes to synchronized block
3. while Thread1 is enters synchronized block, Thread2 checks instance is null and tries to go further
4. while Thread1 complete execution of synchronized block Thread2 waits.
5. the moment Thread1 completes synchronized block(i.e DB instance is created first time), Thread2 enters synchronized block
6. Thread2 creates another instance of `AppDatabase` (`i.e 2nd instance got created and replaced previous one`) (it's where flaw exists in current singleton pattern not being properly written)

### Solution
Implement double-checked singleton the way it is implemented (Just by rechecking inside synchronized block to ensure instance is not already created)

### References:

1. [https://en.wikipedia.org/wiki/Double-checked_locking](https://en.wikipedia.org/wiki/Double-checked_locking)
2. [https://www.baeldung.com/kotlin/singleton-classes#1-companion-object](https://www.baeldung.com/kotlin/singleton-classes#1-companion-object)

### PR DESCRIPTION
**Pull request by Himanshu-Kandwal**
- Ensures Room DB initialization happens only once by implementing double-checked locking
- Only file that's changed is  `AppDatabase.kt`
- fixes #130

### CODE REVIEW

File: app/src/main/java/org/nsh07/pomodoro/data/AppDatabase.kt [hunk 1]
```diff
@@ -34,9 +32,8 @@ abstract class AppDatabase : RoomDatabase() {
 
         fun getDatabase(context: Context): AppDatabase {
             return Instance ?: synchronized(this) {
-                Room.databaseBuilder(context, AppDatabase::class.java, "app_database")
-                    .build()
-                    .also { Instance = it }
+                Instance ?: Room.databaseBuilder(context, AppDatabase::class.java, "app_database")
+                    .build().also { Instance = it }
```
Comment (nsh07) [inline app/src/main/java/org/nsh07/pomodoro/data/AppDatabase.kt]: Just a minor style suggestion: can you please move the `.also` block to the next line for a consistent code style? Thanks!

**Review by nsh07 — CHANGES_REQUESTED** [review]

**Comment by Himanshu-Kandwal** [comment]
All Suggested Changes Done, 
**ready for re-review**. @nsh07
