### PR TITLE
feat:Fix issue where screen does not wake up when the timer ends

### LINKED ISSUE #46: Alarm should wake up screen
I usually close my screen when using the app. When the timer ends and alarm starts, the screen doesn't wake up. I need to insert my pin/my fingerprint and then start the following phase.
Perhaps add a setting to wake up screen on alarm, if possible?

### PR DESCRIPTION
**Pull request by Fandroid745**
Fixes #46

### CODE REVIEW

File: app/src/main/java/org/nsh07/pomodoro/service/TimerService.kt [hunk 1]
```diff
@@ -117,6 +124,7 @@ class TimerService : Service() {
         return super.onStartCommand(intent, flags, startId)
     }
 
+    @Suppress("DEPRECATION")
```
Comment (nsh07) [inline app/src/main/java/org/nsh07/pomodoro/service/TimerService.kt]: Can you please replace whatever is deprecated with the corresponding replacement?
